import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";

import GlobalNavBar from "./_components/GlobalNavBar";
import SideNavBar from "./_components/SideNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col md:flex-row w-full h-screen`}
      >
        <GlobalNavBar />
        <SideNavBar />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
